### ISSUE TITLE
"default_context" missing for certain items

### ISSUE THREAD

**Issue by haraldkofler** [gs1/GS1_DigitalLink_Resolver_CE#10]
I just tried to query the gs1 resolver for the EAN 761003200001 with this URL:

`https://id.gs1.org/gtin/07610032000010?linkType=all`

Within in the "relatedvideo" section of the JSON answer I get the default_context item only for the french language. For the german and english language sections the default_context is missing.
AFAIK the default_context should be included for every language.
This would be important the allow my app barValid to dynamically parse all linktypes.

**Comment by nicklansley** [comment]
I've added an extra function to the BUILD task (ClassBuild.php) which checks for missing defaults and, if any is missing, choose the first entry in the array as the default. This happens at every level (linktype, lang, context and mime-type).
I'm closing the issue now although I will add to the backlog a 'retro fit' of data back into the data-entry database by setting the default flag so that the source data always has an appropriate default.
