### ISSUE TITLE
Context/nesting problem

### ISSUE THREAD

**Issue by philarcher** [gs1/GS1_DigitalLink_Resolver_CE#13]
I've put a bunch of links in the GS1 GO resolver for 04061622828126.

Default
linkType=pip
language=fr
context=fr
https://www.adidas.fr/chaussure-advantage/EF0301.html

linkType=pip
language=sv
context=se
https://www.adidas.se/advantage-shoes/EF0301.html

linkType=pip
language=en
context=gb
https://www.adidas.co.uk/advantage-shoes/EF0301.html

linkType=hasRetailers
language=fr
context=fr
https://www.decathlon.fr/p/advantage-blanc-vert/_/R-p-X8555624?mc=8555624

linkType=relatedVideo
language=en
context=gb
https://www.youtube.com/watch?v=MDXuvEdE1aA

OK, the related video and has retailers I'm not bothered about here except to note that I *really* don't want to indicate any lang or context for the video.

The issue is the multiple product info pages.

This URL https://id.gs1.org/gtin/04061622828126?context=se
gives me the default (French) page. In order to get the Swedish I have to make it https://id.gs1.org/gtin/04061622828126?context=se&lang=sv (i..e declare the language as well).
IMO, I should get the Swedish page if I just give the context.

Meanwhile even https://id.gs1.org/gtin/04061622828126?context=gb&lang=en sends me to the French page.

Hmm...

I think this comes from *requiring* a value for everything. I think if the link type is defined in the query, everything else can be blank.

WDYT?

**Comment by RalphTro** [comment]
Dear Phil,

First of all, I’d like to wish you a Happy New Year 2020! Hope you have a great start into the twenties.

Thanks also for preparing these examples. In trying them out, it seems that you actually use e.g. ‘pip’ and ‘hasRetailers’ as rel attribute values.

However, it was my understanding so far that all standard values need to be prefixed with ‘gs1’ (i.e. resulting in e.g. https://id.gs1.org/01/04061622828126?linkType=gs1:hasRetailers rather than https://id.gs1.org/01/04061622828126?linkType=hasRetailers). Note that only the latter resolves to the Decathlon site.

Thanks in advance for your feedback and kind regards,
Ralph

Von: Phil Archer <notifications@github.com>
Gesendet: Freitag, 20. Dezember 2019 17:32
An: gs1/GS1_DigitalLink_Resolver_CE <GS1_DigitalLink_Resolver_CE@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [gs1/GS1_DigitalLink_Resolver_CE] Context/nesting problem (#13)


I've put a bunch of links in the GS1 GO resolver for 04061622828126.

Default
linkType=pip
language=fr
context=fr
https://www.adidas.fr/chaussure-advantage/EF0301.html

linkType=pip
language=sv
context=se
https://www.adidas.se/advantage-shoes/EF0301.html

linkType=pip
language=en
context=gb
https://www.adidas.co.uk/advantage-shoes/EF0301.html

linkType=hasRetailers
language=fr
context=fr
https://www.decathlon.fr/p/advantage-blanc-vert/_/R-p-X8555624?mc=8555624

linkType=relatedVideo
language=en
context=gb
https://www.youtube.com/watch?v=MDXuvEdE1aA

OK, the related video and has retailers I'm not bothered about here except to note that I really don't want to indicate any lang or context for the video.

The issue is the multiple product info pages.

This URL https://id.gs1.org/gtin/04061622828126?context=se
gives me the default (French) page. In order to get the Swedish I have to make it https://id.gs1.org/gtin/04061622828126?context=se&lang=sv (i..e declare the language as well).
IMO, I should get the Swedish page if I just give the context.

Meanwhile even https://id.gs1.org/gtin/04061622828126?context=gb&lang=en sends me to the French page.

Hmm...

I think this comes from requiring a value for everything. I think if the link type is defined in the query, everything else can be blank.

WDYT?

**Comment by philarcher** [comment]
Happy new year to you too, Ralph.

You are correct to say that the linkTypes should be prefixed with gs1:. More precisely, they are compact URIs. They are also case sensitive. I have mentioned this to @nicklansley once or twice... It's also in the system as Issue #4 :-)

**Comment by philarcher** [comment]
Tidying up old issues. This was done ages ago. This is the kind of discussion that led to the use of linkset (now implemented on dv1). I'm happy :-)
