### ISSUE TITLE
Titles of link headers

### ISSUE THREAD

**Issue by philarcher** [gs1/GS1_DigitalLink_Resolver_CE#2]
The titles of links exposed in the link headers are showing as the full URL of the link type, e.g. https://gs1.org/voc/pip, rather than the title (this one should be Product information page for example). Try curl -I https://id.gs1.org/gtin/9506000134352 to see this.

**Comment by nicklansley** [comment]
Updated service to use the 'official' linktype-name if no 'friendly' name is used by the data-entry user. This affects the 'title' value of the JSON output and all 'title' entries in the HTTP header links. The update required a rewrite of the stored procedure [BUILD_GetURIResponses] to left-join the responses table with the linktypes table to get the 'official' information during the BUILD task.
All existing entries in the database had their api_builder_processed flags set to 0 after the updated containers were rebuilt and restarted in order to rebuild all resolver documents.
