### ISSUE TITLE
sqldb_create_script.sql': Invalid filename

### ISSUE THREAD

**Issue by swalde** [gs1/GS1_DigitalLink_Resolver_CE#63]
on page 20 in "GS1 Resolver - Overview and Architecture.pdf" 
command: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P its@SECR3T! -i /gs1resolver_sql_scripts/sqldb_create_script.sql
does not work 
Error: Sqlcmd: '/gs1resolver_sql_scripts/sqldb_create_script.sql': Invalid filename.

**Comment by swaldegs1** [comment]
Goes for me to

**Comment by swaldegs1** [comment]
Problem solved using SSMS from the hosting Labtop having SQL Server Management Studio SSMS installed on hosting Window 11 box, then run this command, using SSMS sqlcmd:
    sqlcmd -S localhost -U 'sa' -P 'its@SECR3T!' -i .\resolver_sql_server\sqldb_create_script.sql

**Comment by ablears** [comment]
The problem is /gs1resolver_sql_scripts/sqldb_create_script.sql is not a valid path when inside the SQL server container. 

So do something like this from the project root:
`docker cp resolver_sql_server/sqldb_create_script.sql YOURSQLCONTAINERID://sqldb_create_script.sql
docker exec -it resolver-sql-server bash
/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P its@SECR3T! -i /sqldb_create_script.sql`

**Comment by abiriadev** [comment]
It would be really helpful if it is documented somewhere.

**Comment by abiriadev** [comment]
I made a PR for this issue: #66
